
/**
 * Generated by Babylon.js Editor
 */

import { loadScene, scriptsDictionary, scriptAssetsCache, _applyScriptsForObject, _removeRegisteredScriptInstance, _preloadScriptsAssets } from "babylonjs-editor-tools";
import * as scripts_box_nique from "./scripts/box_nique";

export const scriptsMap = {
    "scripts/box_nique.ts": scripts_box_nique
};

export { loadScene, scriptsDictionary, scriptAssetsCache, _applyScriptsForObject, _removeRegisteredScriptInstance, _preloadScriptsAssets };
